ALTER TABLE guilds
ADD COLUMN crole_available INTEGER NOT NULL DEFAULT(-1);

ALTER TABLE guilds
ADD COLUMN crole_price INTEGER NOT NULL DEFAULT(10000);

ALTER TABLE guilds
ADD COLUMN cemoji_available INTEGER NOT NULL DEFAULT(-1);

ALTER TABLE guilds
ADD COLUMN cemoji_price INTEGER NOT NULL DEFAULT(10000);

